# Generated by Django 4.0.3 on 2022-04-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfb',
            name='product',
        ),
        migrations.AddField(
            model_name='general_product',
            name='feedback',
            field=models.ManyToManyField(to='main.productfb'),
        ),
    ]
