# Generated by Django 4.0.3 on 2022-04-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_productfb_product_general_product_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.CreateModel(
            name='SellerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='main.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='seller_order',
            field=models.ManyToManyField(to='main.sellerorder'),
        ),
    ]
