# Generated by Django 4.0.3 on 2022-04-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_payment_user_remove_refund_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_product',
            name='proved',
            field=models.BooleanField(default=True),
        ),
    ]
