# Generated by Django 4.0.3 on 2022-04-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_order_items_sellerorder_order_seller_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_order',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='main.orderitem'),
        ),
        migrations.DeleteModel(
            name='SellerOrder',
        ),
    ]
