# Generated by Django 4.0.3 on 2022-04-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_orderitem_fulfill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='fulfill_date',
            field=models.DateTimeField(null=True),
        ),
    ]
