# Generated by Django 4.0.3 on 2022-04-11 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_orderitem_fulfill_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfb',
            name='israted',
        ),
        migrations.AddField(
            model_name='productfb',
            name='helpful',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SellerFB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.CharField(blank=True, max_length=1024, null=True)),
                ('helpful', models.IntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
