# Generated by Django 4.0.3 on 2022-04-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_productfb_israted_productfb_helpful_sellerfb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
